{% set name = "lockfile" %}
{% set version = "0.12.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - pbr >=1.8
  run:
    - python

test:
  imports:
    - lockfile
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://launchpad.net/pylockfile
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Platform-independent file locking module
  description: |
    lockfile exports a LockFile class which provides a simple API for locking files.
  doc_url: https://launchpad.net/pylockfile
  dev_url: https://opendev.org/openstack/pylockfile/